### ISSUE TITLE
ModuleNotFoundError: No module named 'src.utils.rigid_utils'

### ISSUE THREAD

**Issue by seankhl** [Ligo-Biosciences/AlphaFold3#39]
When attempting to run `python -m src.train_alphafold`, the above error is triggered. Upon further inspection, the file corresponding to this module is not present.

The full error is reproduced below:

```
/nix/store/qljnv45b7p1417yk864hr5gg83lpbzl6-python3-3.9.19-env/lib/python3.9/site-packages/torch/cuda/__init__.py:843: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  r = torch._C._cuda_getDeviceCount() if nvml_count < 0 else nvml_count
[2024-09-06 17:45:24,738] [WARNING] [real_accelerator.py:162:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2024-09-06 17:45:24,746] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cpu (auto detect)
[2024-09-06 17:45:25,355][src.utils.utils][INFO] - [rank: 0] Enforcing tags! <cfg.extras.enforce_tags=True>
[2024-09-06 17:45:25,359][__main__][INFO] - [rank: 0] Instantiating datamodule <src.data.data_modules.OpenFoldDataModule>
[2024-09-06 17:45:25,628][src.utils.utils][ERROR] - [rank: 0]
Traceback (most recent call last):
  File "/nix/store/qljnv45b7p1417yk864hr5gg83lpbzl6-python3-3.9.19-env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'src.data' has no attribute 'data_modules'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/qljnv45b7p1417yk864hr5gg83lpbzl6-python3-3.9.19-env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/nix/store/isd0gr7kdg9y0qn1hiywh3v61v3r65w8-python3-3.9.19/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/machineer/repos/upstream/AlphaFold3/src/data/data_modules.py", line 29, in <module>
    from src.data import (
  File "/home/machineer/repos/upstream/AlphaFold3/src/data/feature_pipeline.py", line 23, in <module>
    from src.data import input_pipeline, input_pipeline_multimer
  File "/home/machineer/repos/upstream/AlphaFold3/src/data/input_pipeline.py", line 18, in <module>
    from src.data import data_transforms
  File "/home/machineer/repos/upstream/AlphaFold3/src/data/data_transforms.py", line 28, in <module>
    from src.utils.rigid_utils import Rigids, Rotations
ModuleNotFoundError: No module named 'src.utils.rigid_utils'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/qljnv45b7p1417yk864hr5gg83lpbzl6-python3-3.9.19-env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/nix/store/qljnv45b7p1417yk864hr5gg83lpbzl6-python3-3.9.19-env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'src.data.data_modules.OpenFoldDataModule':
ModuleNotFoundError("No module named 'src.utils.rigid_utils'")
Are you sure that 'data_modules' is importable from module 'src.data'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/machineer/repos/upstream/AlphaFold3/src/utils/utils.py", line 68, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/machineer/repos/upstream/AlphaFold3/src/train_alphafold.py", line 53, in train
    datamodule: LightningDataModule = hydra.utils.instantiate(cfg.data)
  File "/nix/store/qljnv45b7p1417yk864hr5gg83lpbzl6-python3-3.9.19-env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/nix/store/qljnv45b7p1417yk864hr5gg83lpbzl6-python3-3.9.19-env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/nix/store/qljnv45b7p1417yk864hr5gg83lpbzl6-python3-3.9.19-env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.data.data_modules.OpenFoldDataModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: data
[2024-09-06 17:45:25,629][src.utils.utils][INFO] - [rank: 0] Output dir: /home/machineer/repos/upstream/AlphaFold3/logs/train/runs/2024-09-06_17-45-25
Error executing job with overrides: []
Error locating target 'src.data.data_modules.OpenFoldDataModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: data

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

The `data_modules` error seems to be spurious, as the `rigid_utils` error triggers it. Perhraps the `rigid_utils.py` file was accidentally ommitted from the git repo?

**Comment by ardagoreci** [comment]
Should be fixed now. The model fully relies on Vec3Array and Rot3Array, and I had deleted this as part of the final refactoring / cleanup before the release. The data pipeline will also soon migrate to Vec3Array / Rot3Array.
